version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - revive
  settings:
    revive:
      rules:
        - name: exported
        - name: blank-imports
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: increment-decrement
        - name: var-naming

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
