// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: ai_worker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIWorker_ParseAndEmbed_FullMethodName = "/raven.ai.v1.AIWorker/ParseAndEmbed"
	AIWorker_QueryRAG_FullMethodName      = "/raven.ai.v1.AIWorker/QueryRAG"
	AIWorker_GetEmbedding_FullMethodName  = "/raven.ai.v1.AIWorker/GetEmbedding"
)

// AIWorkerClient is the client API for AIWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIWorkerClient interface {
	ParseAndEmbed(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
	QueryRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RAGChunk], error)
	GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
}

type aIWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAIWorkerClient(cc grpc.ClientConnInterface) AIWorkerClient {
	return &aIWorkerClient{cc}
}

func (c *aIWorkerClient) ParseAndEmbed(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, AIWorker_ParseAndEmbed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIWorkerClient) QueryRAG(ctx context.Context, in *RAGRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RAGChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIWorker_ServiceDesc.Streams[0], AIWorker_QueryRAG_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RAGRequest, RAGChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIWorker_QueryRAGClient = grpc.ServerStreamingClient[RAGChunk]

func (c *aIWorkerClient) GetEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, AIWorker_GetEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIWorkerServer is the server API for AIWorker service.
// All implementations must embed UnimplementedAIWorkerServer
// for forward compatibility.
type AIWorkerServer interface {
	ParseAndEmbed(context.Context, *ParseRequest) (*ParseResponse, error)
	QueryRAG(*RAGRequest, grpc.ServerStreamingServer[RAGChunk]) error
	GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	mustEmbedUnimplementedAIWorkerServer()
}

// UnimplementedAIWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIWorkerServer struct{}

func (UnimplementedAIWorkerServer) ParseAndEmbed(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseAndEmbed not implemented")
}
func (UnimplementedAIWorkerServer) QueryRAG(*RAGRequest, grpc.ServerStreamingServer[RAGChunk]) error {
	return status.Errorf(codes.Unimplemented, "method QueryRAG not implemented")
}
func (UnimplementedAIWorkerServer) GetEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmbedding not implemented")
}
func (UnimplementedAIWorkerServer) mustEmbedUnimplementedAIWorkerServer() {}
func (UnimplementedAIWorkerServer) testEmbeddedByValue()                  {}

// UnsafeAIWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIWorkerServer will
// result in compilation errors.
type UnsafeAIWorkerServer interface {
	mustEmbedUnimplementedAIWorkerServer()
}

func RegisterAIWorkerServer(s grpc.ServiceRegistrar, srv AIWorkerServer) {
	// If the following call pancis, it indicates UnimplementedAIWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIWorker_ServiceDesc, srv)
}

func _AIWorker_ParseAndEmbed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWorkerServer).ParseAndEmbed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWorker_ParseAndEmbed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWorkerServer).ParseAndEmbed(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIWorker_QueryRAG_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RAGRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIWorkerServer).QueryRAG(m, &grpc.GenericServerStream[RAGRequest, RAGChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIWorker_QueryRAGServer = grpc.ServerStreamingServer[RAGChunk]

func _AIWorker_GetEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWorkerServer).GetEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWorker_GetEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWorkerServer).GetEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIWorker_ServiceDesc is the grpc.ServiceDesc for AIWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raven.ai.v1.AIWorker",
	HandlerType: (*AIWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseAndEmbed",
			Handler:    _AIWorker_ParseAndEmbed_Handler,
		},
		{
			MethodName: "GetEmbedding",
			Handler:    _AIWorker_GetEmbedding_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryRAG",
			Handler:       _AIWorker_QueryRAG_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai_worker.proto",
}
