import { defineConfig } from "vitepress";
import { mainSidebar } from "./sidebars/main";
import { apiSidebar } from "./openapi";

export default defineConfig({
  title: "Raven Docs",
  description:
    "Open-source multi-tenant knowledge base platform with AI chat, voice, and WhatsApp.",
  lang: "en-US",
  cleanUrls: true,
  lastUpdated: true,

  // Read content from .tmp/, populated by scripts/sync-content.ts at
  // build time. T2 ships this empty; T4 wires the sync.
  srcDir: ".tmp",

  // The API overview links to per-operation pages that vitepress-openapi
  // generates dynamically (and to the local-dev server's autolink). Both
  // are valid at runtime but the static dead-link checker can't see them.
  ignoreDeadLinks: [
    /^https?:\/\/localhost(?::\d+)?/,
    /^\/api\//,
  ],

  // VitePress resolves `public/` relative to srcDir, but our public
  // assets (robots.txt, future favicons) live in the real source tree
  // at docs-site/public/, not the synthetic .tmp/. Point Vite at the
  // real dir so static files are copied verbatim into dist/.
  vite: {
    publicDir: "../public",
    build: {
      rollupOptions: {
        // The 404 page dynamically imports PageFind's UI bundle at
        // runtime; the file is generated by `pagefind --site` AFTER
        // Vite finishes, so Rollup can't resolve it during the build.
        external: [/^\/_pagefind\//],
      },
    },
  },

  sitemap: {
    hostname: "https://docs.raven.ravencloak.org",
    // Drop the 404 page from the sitemap — search engines should not be
    // told to index the not-found page. VitePress emits the url as a
    // relative path (e.g. `404`, `404.html`) without a leading slash,
    // so match the bare segment.
    transformItems: (items) =>
      items.filter((i) => !/(^|\/)404(\.html)?$/.test(i.url)),
  },

  head: [
    ["link", { rel: "icon", href: "/favicon.svg", type: "image/svg+xml" }],
    ["meta", { name: "theme-color", content: "#e11d48" }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "Raven Docs" }],
  ],

  themeConfig: {
    nav: [
      { text: "Get Started", link: "/get-started/installation" },
      { text: "Guides", link: "/guides/workspaces-and-tenancy" },
      { text: "Concepts", link: "/concepts/architecture" },
      { text: "API", link: "/api/overview" },
      { text: "Contributing", link: "/contributing/overview" },
    ],

    // Sidebar contributions are merged in by T5 (main IA) and T6 (API).
    sidebar: {
      ...mainSidebar,
      "/api/": apiSidebar,
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/ravencloak-org/Raven" },
    ],

    editLink: {
      // Edit-on-GitHub points at the SOURCE markdown in docs/ or the
      // repo root, not the synced .tmp/ copy. T4 wires the path
      // rewrite when sync-content runs.
      pattern:
        "https://github.com/ravencloak-org/Raven/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },

    footer: {
      message:
        'Released under the <a href="https://github.com/ravencloak-org/Raven/blob/main/LICENSE">Apache 2.0 License</a>. Spotted an error? <a href="https://github.com/ravencloak-org/Raven/issues/new">Open an issue</a>.',
      copyright: `Copyright © 2026-present <a href="https://github.com/ravencloak-org/Raven">Ravencloak Org</a>`,
    },

    search: {
      provider: "local",
    },
  },
});
