-- ============================================================================
-- Atlas-managed canonical schema for Raven (schema-as-code).
--
-- DO NOT EDIT BY HAND. Regenerate with:  make schema-inspect
--
-- This file is the declarative, version-controlled snapshot of the Postgres
-- schema, produced verbatim by `atlas schema inspect` against a database that
-- has had ALL goose migrations in migrations/ applied. It is the Dolt-like
-- artifact: `git diff` / `git blame` / branch / merge the schema shape here.
--
-- goose REMAINS the applier of record (Makefile `migrate-up`). Atlas does NOT
-- apply migrations at runtime; it only provides schema version-control review.
-- See docs/adr/0010-atlas-schema-version-control.md.
--
-- EXTENSIONS are owned by migrations/00001_extensions_and_types.sql, which runs:
--     CREATE EXTENSION "uuid-ossp";
--     CREATE EXTENSION "vector";   -- pgvector, enables vector(768) + HNSW below
--     CREATE EXTENSION "pg_trgm";
-- They are intentionally NOT re-emitted as executable DDL in this file: the
-- free-tier `atlas` binary rejects CREATE EXTENSION in a declarative schema
-- source ("extensions are available to logged-in users only"), and re-emitting
-- them would break `make schema-diff`. The pgvector round-trip is proven below
-- by the vector(768) columns and the `USING HNSW (... vector_cosine_ops)`
-- indexes, which Atlas inspected and reproduces faithfully. The Atlas dev-url
-- used by `make schema-inspect` / `make schema-diff` pre-installs these three
-- extensions (and the raven_app / raven_admin roles) so the schema materialises.
-- ============================================================================

-- Create enum type "org_status"
CREATE TYPE "org_status" AS ENUM ('active', 'suspended', 'deactivated');
-- Create enum type "user_status"
CREATE TYPE "user_status" AS ENUM ('active', 'disabled');
-- Create enum type "workspace_role"
CREATE TYPE "workspace_role" AS ENUM ('owner', 'admin', 'member', 'viewer');
-- Create enum type "kb_status"
CREATE TYPE "kb_status" AS ENUM ('active', 'archived', 'read_only_private', 'dmca_pending');
-- Create enum type "processing_status"
CREATE TYPE "processing_status" AS ENUM ('queued', 'crawling', 'parsing', 'chunking', 'embedding', 'ready', 'failed', 'reprocessing');
-- Create enum type "source_type"
CREATE TYPE "source_type" AS ENUM ('url', 'sitemap', 'rss_feed', 'web_page', 'web_site');
-- Create enum type "crawl_frequency"
CREATE TYPE "crawl_frequency" AS ENUM ('manual', 'daily', 'weekly', 'monthly');
-- Create enum type "chunk_type"
CREATE TYPE "chunk_type" AS ENUM ('text', 'table', 'image_caption', 'code');
-- Create enum type "llm_provider"
CREATE TYPE "llm_provider" AS ENUM ('openai', 'anthropic', 'cohere', 'google', 'azure_openai', 'custom', 'ollama');
-- Create enum type "provider_status"
CREATE TYPE "provider_status" AS ENUM ('active', 'revoked', 'expired');
-- Create enum type "api_key_status"
CREATE TYPE "api_key_status" AS ENUM ('active', 'revoked');
-- Create enum type "message_role"
CREATE TYPE "message_role" AS ENUM ('user', 'assistant', 'system');
-- Create enum type "routing_mode"
CREATE TYPE "routing_mode" AS ENUM ('static', 'column_based', 'auto');
-- Create enum type "connector_status"
CREATE TYPE "connector_status" AS ENUM ('active', 'paused', 'error', 'deleted');
-- Create enum type "sync_mode"
CREATE TYPE "sync_mode" AS ENUM ('full_refresh', 'incremental', 'cdc');
-- Create enum type "security_rule_type"
CREATE TYPE "security_rule_type" AS ENUM ('ip_allowlist', 'ip_denylist', 'geo_block', 'pattern_match', 'rate_override');
-- Create enum type "security_action"
CREATE TYPE "security_action" AS ENUM ('allow', 'block', 'throttle', 'log', 'alert');
-- Create enum type "webhook_status"
CREATE TYPE "webhook_status" AS ENUM ('active', 'paused', 'failed');
-- Create enum type "stranger_status"
CREATE TYPE "stranger_status" AS ENUM ('active', 'throttled', 'blocked', 'banned');
-- Create enum type "notification_type"
CREATE TYPE "notification_type" AS ENUM ('conversation_summary', 'admin_digest', 'custom');
-- Create enum type "notification_status"
CREATE TYPE "notification_status" AS ENUM ('pending', 'sent', 'failed');
-- Create enum type "voice_session_state"
CREATE TYPE "voice_session_state" AS ENUM ('created', 'active', 'ended');
-- Create enum type "voice_speaker"
CREATE TYPE "voice_speaker" AS ENUM ('agent', 'user');
-- Create enum type "whatsapp_call_direction"
CREATE TYPE "whatsapp_call_direction" AS ENUM ('inbound', 'outbound');
-- Create enum type "whatsapp_call_state"
CREATE TYPE "whatsapp_call_state" AS ENUM ('ringing', 'connected', 'ended');
-- Create enum type "kb_visibility"
CREATE TYPE "kb_visibility" AS ENUM ('private', 'public');
-- Create "goose_db_version" table
CREATE TABLE "goose_db_version" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "version_id" bigint NOT NULL,
  "is_applied" boolean NOT NULL,
  "tstamp" timestamp NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create "organizations" table
CREATE TABLE "organizations" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "name" character varying(255) NOT NULL,
  "slug" character varying(64) NOT NULL,
  "status" "org_status" NOT NULL DEFAULT 'active',
  "settings" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "takedown_strikes" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "organizations_slug_key" UNIQUE ("slug"),
  CONSTRAINT "organizations_slug_format_check" CHECK ((slug)::text ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text)
);
-- Create index "idx_organizations_slug" to table: "organizations"
CREATE INDEX "idx_organizations_slug" ON "organizations" ("slug");
-- Create index "idx_organizations_status" to table: "organizations"
CREATE INDEX "idx_organizations_status" ON "organizations" ("status");
-- Create "users" table
CREATE TABLE "users" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NULL,
  "email" character varying(255) NOT NULL,
  "display_name" character varying(255) NULL,
  "external_id" character varying(255) NULL,
  "status" "user_status" NOT NULL DEFAULT 'active',
  "last_login_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "auth_provider" text NOT NULL DEFAULT 'supertokens',
  PRIMARY KEY ("id"),
  CONSTRAINT "users_keycloak_sub_key" UNIQUE ("external_id"),
  CONSTRAINT "users_org_id_email_key" UNIQUE ("org_id", "email"),
  CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_users_email" to table: "users"
CREATE INDEX "idx_users_email" ON "users" ("email");
-- Create index "idx_users_external_id" to table: "users"
CREATE UNIQUE INDEX "idx_users_external_id" ON "users" ("external_id") WHERE (external_id IS NOT NULL);
-- Create index "idx_users_org_id" to table: "users"
CREATE INDEX "idx_users_org_id" ON "users" ("org_id");
-- Create "account_purge_warnings" table
CREATE TABLE "account_purge_warnings" (
  "user_id" uuid NOT NULL,
  "warned_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id"),
  CONSTRAINT "account_purge_warnings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "workspaces" table
CREATE TABLE "workspaces" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "slug" character varying(100) NOT NULL,
  "settings" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "email_summaries_enabled" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "workspaces_org_id_slug_key" UNIQUE ("org_id", "slug"),
  CONSTRAINT "workspaces_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_workspaces_org_id" to table: "workspaces"
CREATE INDEX "idx_workspaces_org_id" ON "workspaces" ("org_id");
-- Create "knowledge_bases" table
CREATE TABLE "knowledge_bases" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "slug" character varying(100) NOT NULL,
  "description" text NULL,
  "settings" jsonb NULL DEFAULT '{}',
  "status" "kb_status" NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "cache_enabled" boolean NOT NULL DEFAULT true,
  "cache_similarity_threshold" real NOT NULL DEFAULT 0.92,
  "visibility" "kb_visibility" NOT NULL DEFAULT 'private',
  "published_at" timestamptz NULL,
  "published_by_user_id" uuid NULL,
  "source_public_kb_id" uuid NULL,
  "imported_from_revision_at" timestamptz NULL,
  "last_modified_at" timestamptz NOT NULL DEFAULT now(),
  "license_spdx_id" text NULL,
  "import_count" integer NOT NULL DEFAULT 0,
  "preview_count" integer NOT NULL DEFAULT 0,
  "search_tsv" tsvector NULL GENERATED ALWAYS AS (setweight(to_tsvector('english'::regconfig, (COALESCE(name, ''::character varying))::text), 'A'::"char") || setweight(to_tsvector('english'::regconfig, COALESCE(description, ''::text)), 'B'::"char")) STORED,
  PRIMARY KEY ("id"),
  CONSTRAINT "knowledge_bases_workspace_id_slug_key" UNIQUE ("workspace_id", "slug"),
  CONSTRAINT "knowledge_bases_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "knowledge_bases_published_by_user_id_fkey" FOREIGN KEY ("published_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "knowledge_bases_source_public_kb_id_fkey" FOREIGN KEY ("source_public_kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "knowledge_bases_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "knowledge_bases_cache_similarity_threshold_check" CHECK ((cache_similarity_threshold >= (0.80)::double precision) AND (cache_similarity_threshold <= (0.99)::double precision)),
  CONSTRAINT "knowledge_bases_public_requires_license" CHECK ((visibility = 'private'::kb_visibility) OR (license_spdx_id IS NOT NULL))
);
-- Create index "idx_kb_last_modified_at_public" to table: "knowledge_bases"
CREATE INDEX "idx_kb_last_modified_at_public" ON "knowledge_bases" ("last_modified_at" DESC) WHERE (visibility = 'public'::kb_visibility);
-- Create index "idx_kb_public_org_slug_uniq" to table: "knowledge_bases"
CREATE UNIQUE INDEX "idx_kb_public_org_slug_uniq" ON "knowledge_bases" ("org_id", "slug") WHERE (visibility = 'public'::kb_visibility);
-- Create index "idx_kb_search_tsv_public" to table: "knowledge_bases"
CREATE INDEX "idx_kb_search_tsv_public" ON "knowledge_bases" USING GIN ("search_tsv") WHERE (visibility = 'public'::kb_visibility);
-- Create index "idx_kb_source_public_kb_id" to table: "knowledge_bases"
CREATE INDEX "idx_kb_source_public_kb_id" ON "knowledge_bases" ("source_public_kb_id") WHERE (source_public_kb_id IS NOT NULL);
-- Create index "idx_kb_visibility_public" to table: "knowledge_bases"
CREATE INDEX "idx_kb_visibility_public" ON "knowledge_bases" ("visibility") WHERE (visibility = 'public'::kb_visibility);
-- Create index "idx_knowledge_bases_org_id" to table: "knowledge_bases"
CREATE INDEX "idx_knowledge_bases_org_id" ON "knowledge_bases" ("org_id");
-- Create index "idx_knowledge_bases_workspace_id" to table: "knowledge_bases"
CREATE INDEX "idx_knowledge_bases_workspace_id" ON "knowledge_bases" ("workspace_id");
-- Create "airbyte_connectors" table
CREATE TABLE "airbyte_connectors" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "connector_type" character varying(100) NOT NULL,
  "config" jsonb NOT NULL DEFAULT '{}',
  "sync_mode" "sync_mode" NOT NULL DEFAULT 'full_refresh',
  "schedule_cron" character varying(100) NULL,
  "status" "connector_status" NOT NULL DEFAULT 'active',
  "last_sync_at" timestamptz NULL,
  "last_sync_status" character varying(50) NULL,
  "last_sync_records" integer NULL DEFAULT 0,
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "airbyte_connectors_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "airbyte_connectors_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "airbyte_connectors_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_airbyte_connectors_kb" to table: "airbyte_connectors"
CREATE INDEX "idx_airbyte_connectors_kb" ON "airbyte_connectors" ("knowledge_base_id");
-- Create index "idx_airbyte_connectors_org" to table: "airbyte_connectors"
CREATE INDEX "idx_airbyte_connectors_org" ON "airbyte_connectors" ("org_id");
-- Create "airbyte_sync_history" table
CREATE TABLE "airbyte_sync_history" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "connector_id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "status" character varying(50) NOT NULL DEFAULT 'running',
  "records_synced" integer NULL DEFAULT 0,
  "records_failed" integer NULL DEFAULT 0,
  "bytes_synced" bigint NULL DEFAULT 0,
  "started_at" timestamptz NOT NULL DEFAULT now(),
  "completed_at" timestamptz NULL,
  "error_message" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "airbyte_sync_history_connector_id_fkey" FOREIGN KEY ("connector_id") REFERENCES "airbyte_connectors" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "airbyte_sync_history_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_sync_history_connector" to table: "airbyte_sync_history"
CREATE INDEX "idx_sync_history_connector" ON "airbyte_sync_history" ("connector_id");
-- Create "api_keys" table
CREATE TABLE "api_keys" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NOT NULL,
  "key_hash" character varying(128) NOT NULL,
  "key_prefix" character varying(20) NOT NULL,
  "name" character varying(255) NOT NULL,
  "allowed_domains" text[] NULL,
  "rate_limit" integer NULL DEFAULT 60,
  "status" "api_key_status" NOT NULL DEFAULT 'active',
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "expires_at" timestamptz NULL,
  "workspace_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "api_keys_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "api_keys_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "api_keys_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "api_keys_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_api_keys_key_hash" to table: "api_keys"
CREATE INDEX "idx_api_keys_key_hash" ON "api_keys" ("key_hash");
-- Create index "idx_api_keys_knowledge_base_id" to table: "api_keys"
CREATE INDEX "idx_api_keys_knowledge_base_id" ON "api_keys" ("knowledge_base_id");
-- Create index "idx_api_keys_org_id" to table: "api_keys"
CREATE INDEX "idx_api_keys_org_id" ON "api_keys" ("org_id");
-- Create index "idx_api_keys_workspace_id" to table: "api_keys"
CREATE INDEX "idx_api_keys_workspace_id" ON "api_keys" ("workspace_id");
-- Create "catalog_metadata" table
CREATE TABLE "catalog_metadata" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "catalog_type" character varying(100) NOT NULL,
  "resource_path" character varying(1000) NOT NULL,
  "labels" jsonb NULL DEFAULT '{}',
  "discovered_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "catalog_metadata_org_id_catalog_type_resource_path_key" UNIQUE ("org_id", "catalog_type", "resource_path"),
  CONSTRAINT "catalog_metadata_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "chat_sessions" table
CREATE TABLE "chat_sessions" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NOT NULL,
  "user_id" uuid NULL,
  "session_token" character varying(255) NOT NULL,
  "metadata" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "expires_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "chat_sessions_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chat_sessions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chat_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "idx_chat_sessions_knowledge_base_id" to table: "chat_sessions"
CREATE INDEX "idx_chat_sessions_knowledge_base_id" ON "chat_sessions" ("knowledge_base_id");
-- Create index "idx_chat_sessions_org_id" to table: "chat_sessions"
CREATE INDEX "idx_chat_sessions_org_id" ON "chat_sessions" ("org_id");
-- Create index "idx_chat_sessions_session_token" to table: "chat_sessions"
CREATE INDEX "idx_chat_sessions_session_token" ON "chat_sessions" ("session_token");
-- Create "chat_messages" table
CREATE TABLE "chat_messages" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "session_id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "role" "message_role" NOT NULL,
  "content" text NOT NULL,
  "token_count" integer NULL,
  "chunk_ids" uuid[] NULL,
  "model_name" character varying(100) NULL,
  "latency_ms" integer NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "chat_messages_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chat_messages_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_chat_messages_org_id" to table: "chat_messages"
CREATE INDEX "idx_chat_messages_org_id" ON "chat_messages" ("org_id");
-- Create index "idx_chat_messages_session_id" to table: "chat_messages"
CREATE INDEX "idx_chat_messages_session_id" ON "chat_messages" ("session_id");
-- Create "documents" table
CREATE TABLE "documents" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NOT NULL,
  "file_name" character varying(500) NOT NULL,
  "file_type" character varying(50) NULL,
  "file_size_bytes" bigint NULL,
  "file_hash" character varying(128) NULL,
  "storage_path" text NULL,
  "processing_status" "processing_status" NOT NULL DEFAULT 'queued',
  "processing_error" text NULL,
  "title" character varying(500) NULL,
  "page_count" integer NULL,
  "metadata" jsonb NULL DEFAULT '{}',
  "uploaded_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "documents_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "documents_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "documents_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "idx_documents_file_hash" to table: "documents"
CREATE INDEX "idx_documents_file_hash" ON "documents" ("file_hash");
-- Create index "idx_documents_knowledge_base_id" to table: "documents"
CREATE INDEX "idx_documents_knowledge_base_id" ON "documents" ("knowledge_base_id");
-- Create index "idx_documents_org_id" to table: "documents"
CREATE INDEX "idx_documents_org_id" ON "documents" ("org_id");
-- Create index "idx_documents_processing_status" to table: "documents"
CREATE INDEX "idx_documents_processing_status" ON "documents" ("processing_status");
-- Create "sources" table
CREATE TABLE "sources" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NOT NULL,
  "source_type" "source_type" NOT NULL,
  "url" text NOT NULL,
  "crawl_depth" integer NULL DEFAULT 1,
  "crawl_frequency" "crawl_frequency" NOT NULL DEFAULT 'manual',
  "processing_status" "processing_status" NOT NULL DEFAULT 'queued',
  "processing_error" text NULL,
  "title" character varying(500) NULL,
  "pages_crawled" integer NULL DEFAULT 0,
  "metadata" jsonb NULL DEFAULT '{}',
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "sources_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "sources_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "sources_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_sources_knowledge_base_id" to table: "sources"
CREATE INDEX "idx_sources_knowledge_base_id" ON "sources" ("knowledge_base_id");
-- Create index "idx_sources_org_id" to table: "sources"
CREATE INDEX "idx_sources_org_id" ON "sources" ("org_id");
-- Create index "idx_sources_processing_status" to table: "sources"
CREATE INDEX "idx_sources_processing_status" ON "sources" ("processing_status");
-- Create "chunks" table
CREATE TABLE "chunks" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NOT NULL,
  "document_id" uuid NULL,
  "source_id" uuid NULL,
  "content" text NOT NULL,
  "chunk_index" integer NOT NULL,
  "token_count" integer NULL,
  "page_number" integer NULL,
  "heading" character varying(500) NULL,
  "chunk_type" "chunk_type" NOT NULL DEFAULT 'text',
  "metadata" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "chunk_hash" character varying(64) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "chunks_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chunks_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chunks_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chunks_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "sources" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chunks_check" CHECK ((document_id IS NOT NULL) OR (source_id IS NOT NULL))
);
-- Create index "idx_chunks_content_fts" to table: "chunks"
CREATE INDEX "idx_chunks_content_fts" ON "chunks" USING GIN ((to_tsvector('english'::regconfig, content)));
-- Create index "idx_chunks_content_heading_fts" to table: "chunks"
CREATE INDEX "idx_chunks_content_heading_fts" ON "chunks" USING GIN ((to_tsvector('english'::regconfig, (((COALESCE(heading, ''::character varying))::text || ' '::text) || content))));
-- Create index "idx_chunks_dedup" to table: "chunks"
CREATE UNIQUE INDEX "idx_chunks_dedup" ON "chunks" ("org_id", "knowledge_base_id", "source_id", "chunk_hash") WHERE (chunk_hash IS NOT NULL);
-- Create index "idx_chunks_document_id" to table: "chunks"
CREATE INDEX "idx_chunks_document_id" ON "chunks" ("document_id");
-- Create index "idx_chunks_heading_fts" to table: "chunks"
CREATE INDEX "idx_chunks_heading_fts" ON "chunks" USING GIN ((to_tsvector('english'::regconfig, (heading)::text))) WHERE (heading IS NOT NULL);
-- Create index "idx_chunks_knowledge_base_id" to table: "chunks"
CREATE INDEX "idx_chunks_knowledge_base_id" ON "chunks" ("knowledge_base_id");
-- Create index "idx_chunks_org_id" to table: "chunks"
CREATE INDEX "idx_chunks_org_id" ON "chunks" ("org_id");
-- Create index "idx_chunks_source_id" to table: "chunks"
CREATE INDEX "idx_chunks_source_id" ON "chunks" ("source_id");
-- Create "conversation_sessions" table
CREATE TABLE "conversation_sessions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "org_id" uuid NOT NULL,
  "kb_id" uuid NOT NULL,
  "user_id" text NOT NULL,
  "channel" text NOT NULL,
  "messages" jsonb NOT NULL DEFAULT '[]',
  "started_at" timestamptz NOT NULL DEFAULT now(),
  "ended_at" timestamptz NULL,
  "summary" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "conversation_sessions_kb_id_fkey" FOREIGN KEY ("kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "conversation_sessions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chk_conversation_sessions_messages_is_array" CHECK (jsonb_typeof(messages) = 'array'::text),
  CONSTRAINT "chk_conversation_sessions_times" CHECK ((ended_at IS NULL) OR (ended_at >= started_at)),
  CONSTRAINT "conversation_sessions_channel_check" CHECK (channel = ANY (ARRAY['chat'::text, 'voice'::text, 'webrtc'::text]))
);
-- Create index "idx_conversation_sessions_kb_user_started" to table: "conversation_sessions"
CREATE INDEX "idx_conversation_sessions_kb_user_started" ON "conversation_sessions" ("kb_id", "user_id", "started_at" DESC);
-- Create index "idx_conversation_sessions_org" to table: "conversation_sessions"
CREATE INDEX "idx_conversation_sessions_org" ON "conversation_sessions" ("org_id");
-- Create "dmca_notices" table
CREATE TABLE "dmca_notices" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "target_kb_id" uuid NOT NULL,
  "notice_text" text NOT NULL,
  "claimant_email" text NOT NULL,
  "claimant_name" text NOT NULL,
  "counter_notice_text" text NULL,
  "counter_notice_submitted_at" timestamptz NULL,
  "counter_notice_window_ends" timestamptz NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "resolved_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "dmca_notices_target_kb_id_fkey" FOREIGN KEY ("target_kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "dmca_notices_notice_text_check" CHECK ((length(notice_text) >= 1) AND (length(notice_text) <= 8192)),
  CONSTRAINT "dmca_notices_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'counter_filed'::text, 'resolved_take_down'::text, 'resolved_keep_up'::text, 'withdrawn'::text]))
);
-- Create index "idx_dmca_notices_sweep" to table: "dmca_notices"
CREATE INDEX "idx_dmca_notices_sweep" ON "dmca_notices" ("status", "counter_notice_window_ends");
-- Create index "idx_dmca_notices_target_kb" to table: "dmca_notices"
CREATE INDEX "idx_dmca_notices_target_kb" ON "dmca_notices" ("target_kb_id");
-- Create "embeddings" table
CREATE TABLE "embeddings" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "chunk_id" uuid NOT NULL,
  "model_name" character varying(100) NOT NULL,
  "model_version" character varying(50) NULL,
  "dimensions" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "embedding" vector(768) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "embeddings_chunk_id_model_name_key" UNIQUE ("chunk_id", "model_name"),
  CONSTRAINT "embeddings_chunk_id_fkey" FOREIGN KEY ("chunk_id") REFERENCES "chunks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "embeddings_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_embeddings_chunk_id" to table: "embeddings"
CREATE INDEX "idx_embeddings_chunk_id" ON "embeddings" ("chunk_id");
-- Create index "idx_embeddings_hnsw" to table: "embeddings"
CREATE INDEX "idx_embeddings_hnsw" ON "embeddings" USING HNSW ("embedding" vector_cosine_ops);
-- Create index "idx_embeddings_org_id" to table: "embeddings"
CREATE INDEX "idx_embeddings_org_id" ON "embeddings" ("org_id");
-- Create "lead_profiles" table
CREATE TABLE "lead_profiles" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "knowledge_base_id" uuid NULL,
  "session_ids" uuid[] NULL DEFAULT '{}',
  "email" character varying(255) NULL,
  "name" character varying(255) NULL,
  "phone" character varying(50) NULL,
  "company" character varying(255) NULL,
  "metadata" jsonb NULL DEFAULT '{}',
  "engagement_score" real NOT NULL DEFAULT 0.0,
  "total_messages" integer NOT NULL DEFAULT 0,
  "total_sessions" integer NOT NULL DEFAULT 1,
  "first_seen_at" timestamptz NOT NULL DEFAULT now(),
  "last_seen_at" timestamptz NOT NULL DEFAULT now(),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "lead_profiles_knowledge_base_id_fkey" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "lead_profiles_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_lead_profiles_org_score" to table: "lead_profiles"
CREATE INDEX "idx_lead_profiles_org_score" ON "lead_profiles" ("org_id", "engagement_score" DESC);
-- Create index "uq_lead_profiles_org_email" to table: "lead_profiles"
CREATE UNIQUE INDEX "uq_lead_profiles_org_email" ON "lead_profiles" ("org_id", "email") WHERE (email IS NOT NULL);
-- Create "llm_provider_configs" table
CREATE TABLE "llm_provider_configs" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "provider" "llm_provider" NOT NULL,
  "display_name" character varying(255) NOT NULL,
  "api_key_encrypted" bytea NULL,
  "api_key_iv" bytea NULL,
  "api_key_hint" character varying(20) NULL,
  "base_url" text NULL,
  "config" jsonb NULL DEFAULT '{}',
  "is_default" boolean NOT NULL DEFAULT false,
  "status" "provider_status" NOT NULL DEFAULT 'active',
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "llm_provider_configs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "llm_provider_configs_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_llm_provider_configs_org_id" to table: "llm_provider_configs"
CREATE INDEX "idx_llm_provider_configs_org_id" ON "llm_provider_configs" ("org_id");
-- Create index "llm_provider_configs_org_provider_uniq" to table: "llm_provider_configs"
CREATE UNIQUE INDEX "llm_provider_configs_org_provider_uniq" ON "llm_provider_configs" ("org_id", "provider");
-- Create "marketplace_reports" table
CREATE TABLE "marketplace_reports" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "reported_kb_id" uuid NOT NULL,
  "reporter_user_id" uuid NULL,
  "reason" text NOT NULL,
  "status" text NOT NULL DEFAULT 'open',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "marketplace_reports_reported_kb_id_fkey" FOREIGN KEY ("reported_kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "marketplace_reports_reporter_user_id_fkey" FOREIGN KEY ("reporter_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "marketplace_reports_reason_check" CHECK ((length(reason) >= 1) AND (length(reason) <= 4000)),
  CONSTRAINT "marketplace_reports_status_check" CHECK (status = ANY (ARRAY['open'::text, 'reviewing'::text, 'resolved'::text, 'dismissed'::text]))
);
-- Create index "idx_marketplace_reports_kb" to table: "marketplace_reports"
CREATE INDEX "idx_marketplace_reports_kb" ON "marketplace_reports" ("reported_kb_id");
-- Create index "idx_marketplace_reports_status" to table: "marketplace_reports"
CREATE INDEX "idx_marketplace_reports_status" ON "marketplace_reports" ("status");
-- Create "marketplace_takedowns" table
CREATE TABLE "marketplace_takedowns" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "target_kb_id" uuid NOT NULL,
  "source" text NOT NULL,
  "notes" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "marketplace_takedowns_target_kb_id_fkey" FOREIGN KEY ("target_kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "marketplace_takedowns_source_check" CHECK (source = ANY (ARRAY['publisher'::text, 'admin'::text, 'dmca'::text]))
);
-- Create index "idx_marketplace_takedowns_target_kb" to table: "marketplace_takedowns"
CREATE INDEX "idx_marketplace_takedowns_target_kb" ON "marketplace_takedowns" ("target_kb_id");
-- Create "notification_configs" table
CREATE TABLE "notification_configs" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "notification_type" "notification_type" NOT NULL,
  "recipients" text[] NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "config" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_notification_configs_org_type" UNIQUE ("org_id", "notification_type"),
  CONSTRAINT "notification_configs_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chk_notification_configs_recipients" CHECK (array_length(recipients, 1) >= 1)
);
-- Create index "idx_notification_configs_org" to table: "notification_configs"
CREATE INDEX "idx_notification_configs_org" ON "notification_configs" ("org_id");
-- Create index "idx_notification_configs_type" to table: "notification_configs"
CREATE INDEX "idx_notification_configs_type" ON "notification_configs" ("org_id", "notification_type") WHERE (enabled = true);
-- Create "notification_log" table
CREATE TABLE "notification_log" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "config_id" uuid NULL,
  "notification_type" "notification_type" NOT NULL,
  "recipient" character varying(255) NOT NULL,
  "subject" character varying(500) NOT NULL,
  "status" "notification_status" NOT NULL DEFAULT 'pending',
  "error_message" text NULL,
  "sent_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "notification_log_config_id_fkey" FOREIGN KEY ("config_id") REFERENCES "notification_configs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "notification_log_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_notification_log_org" to table: "notification_log"
CREATE INDEX "idx_notification_log_org" ON "notification_log" ("org_id");
-- Create index "idx_notification_log_status" to table: "notification_log"
CREATE INDEX "idx_notification_log_status" ON "notification_log" ("org_id", "status");
-- Create index "idx_notification_log_time" to table: "notification_log"
CREATE INDEX "idx_notification_log_time" ON "notification_log" ("org_id", "created_at" DESC);
-- Create "org_slug_holds" table
CREATE TABLE "org_slug_holds" (
  "slug" character varying(64) NOT NULL,
  "org_id" uuid NOT NULL,
  "held_until" timestamptz NOT NULL,
  PRIMARY KEY ("slug"),
  CONSTRAINT "org_slug_holds_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "org_slug_holds_slug_format_check" CHECK ((slug)::text ~ '^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$'::text)
);
-- Create index "idx_org_slug_holds_org_id" to table: "org_slug_holds"
CREATE INDEX "idx_org_slug_holds_org_id" ON "org_slug_holds" ("org_id");
-- Create "payment_events" table
CREATE TABLE "payment_events" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "org_id" uuid NOT NULL,
  "event_type" text NOT NULL,
  "payment_id" text NOT NULL,
  "status" text NOT NULL,
  "raw_payload" jsonb NULL,
  "processed_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "payment_events_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_payment_events_idempotent" to table: "payment_events"
CREATE UNIQUE INDEX "idx_payment_events_idempotent" ON "payment_events" ("payment_id", "event_type");
-- Create "payment_intents" table
CREATE TABLE "payment_intents" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "org_id" uuid NOT NULL,
  "amount" bigint NOT NULL,
  "currency" text NOT NULL DEFAULT 'INR',
  "status" text NOT NULL DEFAULT 'requires_payment_method',
  "hyperswitch_payment_id" text NULL,
  "client_secret" text NULL,
  "idempotency_key" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "payment_intents_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "payment_intents_status_check" CHECK (status = ANY (ARRAY['requires_payment_method'::text, 'processing'::text, 'succeeded'::text, 'failed'::text, 'canceled'::text]))
);
-- Create index "idx_payment_intents_hs_payment_id" to table: "payment_intents"
CREATE UNIQUE INDEX "idx_payment_intents_hs_payment_id" ON "payment_intents" ("hyperswitch_payment_id") WHERE (hyperswitch_payment_id IS NOT NULL);
-- Create index "idx_payment_intents_org_id" to table: "payment_intents"
CREATE INDEX "idx_payment_intents_org_id" ON "payment_intents" ("org_id");
-- Create "processing_events" table
CREATE TABLE "processing_events" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "document_id" uuid NULL,
  "source_id" uuid NULL,
  "from_status" character varying(20) NULL,
  "to_status" character varying(20) NOT NULL,
  "error_message" text NULL,
  "duration_ms" integer NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "processing_events_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "processing_events_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "processing_events_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "sources" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_processing_events_doc_timeline" to table: "processing_events"
CREATE INDEX "idx_processing_events_doc_timeline" ON "processing_events" ("document_id", "created_at");
-- Create index "idx_processing_events_document_id" to table: "processing_events"
CREATE INDEX "idx_processing_events_document_id" ON "processing_events" ("document_id");
-- Create index "idx_processing_events_org_id" to table: "processing_events"
CREATE INDEX "idx_processing_events_org_id" ON "processing_events" ("org_id");
-- Create index "idx_processing_events_source_id" to table: "processing_events"
CREATE INDEX "idx_processing_events_source_id" ON "processing_events" ("source_id");
-- Create index "idx_processing_events_source_timeline" to table: "processing_events"
CREATE INDEX "idx_processing_events_source_timeline" ON "processing_events" ("source_id", "created_at");
-- Create "response_cache" table
CREATE TABLE "response_cache" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "kb_id" uuid NOT NULL,
  "query_text" text NOT NULL,
  "response_text" text NOT NULL,
  "sources" jsonb NULL DEFAULT '[]',
  "model_name" character varying(100) NULL,
  "hit_count" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "expires_at" timestamptz NOT NULL DEFAULT (now() + '7 days'::interval),
  "metadata" jsonb NOT NULL DEFAULT '{}',
  "query_embedding" vector(768) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "response_cache_kb_id_fkey" FOREIGN KEY ("kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "response_cache_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_response_cache_embedding" to table: "response_cache"
CREATE INDEX "idx_response_cache_embedding" ON "response_cache" USING HNSW ("query_embedding" vector_cosine_ops);
-- Create index "idx_response_cache_expires" to table: "response_cache"
CREATE INDEX "idx_response_cache_expires" ON "response_cache" ("expires_at");
-- Create index "idx_response_cache_kb_expires" to table: "response_cache"
CREATE INDEX "idx_response_cache_kb_expires" ON "response_cache" ("kb_id", "expires_at");
-- Create index "idx_response_cache_org_kb" to table: "response_cache"
CREATE INDEX "idx_response_cache_org_kb" ON "response_cache" ("org_id", "kb_id");
-- Create "routing_rules" table
CREATE TABLE "routing_rules" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "description" text NULL,
  "source_type" character varying(100) NOT NULL,
  "source_identifier" character varying(500) NULL,
  "routing_mode" "routing_mode" NOT NULL DEFAULT 'static',
  "target_kb_id" uuid NULL,
  "discriminator_column" character varying(255) NULL,
  "column_mappings" jsonb NULL DEFAULT '{}',
  "classification_prompt" text NULL,
  "classification_model" character varying(100) NULL,
  "classification_provider" character varying(50) NULL,
  "priority" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "routing_rules_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "routing_rules_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "routing_rules_target_kb_id_fkey" FOREIGN KEY ("target_kb_id") REFERENCES "knowledge_bases" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "idx_routing_rules_org" to table: "routing_rules"
CREATE INDEX "idx_routing_rules_org" ON "routing_rules" ("org_id");
-- Create index "idx_routing_rules_source" to table: "routing_rules"
CREATE INDEX "idx_routing_rules_source" ON "routing_rules" ("org_id", "source_type", "source_identifier");
-- Create "scheduled_deletes" table
CREATE TABLE "scheduled_deletes" (
  "user_id" uuid NOT NULL,
  "requested_at" timestamptz NOT NULL DEFAULT now(),
  "run_at" timestamptz NOT NULL DEFAULT (now() + '24:00:00'::interval),
  PRIMARY KEY ("user_id"),
  CONSTRAINT "scheduled_deletes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "scheduled_deletes_run_at_idx" to table: "scheduled_deletes"
CREATE INDEX "scheduled_deletes_run_at_idx" ON "scheduled_deletes" ("run_at");
-- Create "security_rules" table
CREATE TABLE "security_rules" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "description" text NULL,
  "rule_type" "security_rule_type" NOT NULL,
  "action" "security_action" NOT NULL DEFAULT 'block',
  "ip_cidrs" text[] NULL,
  "country_codes" text[] NULL,
  "pattern_config" jsonb NULL DEFAULT '{}',
  "rate_limit" integer NULL,
  "rate_window_seconds" integer NULL,
  "priority" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "hits_count" bigint NOT NULL DEFAULT 0,
  "last_hit_at" timestamptz NULL,
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "security_rules_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "security_rules_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_security_rules_org" to table: "security_rules"
CREATE INDEX "idx_security_rules_org" ON "security_rules" ("org_id");
-- Create index "idx_security_rules_type" to table: "security_rules"
CREATE INDEX "idx_security_rules_type" ON "security_rules" ("org_id", "rule_type") WHERE (is_active = true);
-- Create "security_events" table
CREATE TABLE "security_events" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "rule_id" uuid NULL,
  "event_type" character varying(50) NOT NULL,
  "ip_address" inet NOT NULL,
  "country_code" character varying(2) NULL,
  "request_path" character varying(1000) NULL,
  "request_method" character varying(10) NULL,
  "user_agent" text NULL,
  "details" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "security_events_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "security_events_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "security_rules" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "idx_security_events_ip" to table: "security_events"
CREATE INDEX "idx_security_events_ip" ON "security_events" ("ip_address");
-- Create index "idx_security_events_org" to table: "security_events"
CREATE INDEX "idx_security_events_org" ON "security_events" ("org_id");
-- Create index "idx_security_events_time" to table: "security_events"
CREATE INDEX "idx_security_events_time" ON "security_events" ("org_id", "created_at" DESC);
-- Create "stranger_users" table
CREATE TABLE "stranger_users" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "session_id" character varying(255) NOT NULL,
  "ip_address" inet NULL,
  "user_agent" text NULL,
  "status" "stranger_status" NOT NULL DEFAULT 'active',
  "block_reason" text NULL,
  "message_count" integer NOT NULL DEFAULT 0,
  "rate_limit_rpm" integer NULL,
  "last_active_at" timestamptz NOT NULL DEFAULT now(),
  "blocked_at" timestamptz NULL,
  "blocked_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "stranger_users_org_id_session_id_key" UNIQUE ("org_id", "session_id"),
  CONSTRAINT "stranger_users_blocked_by_fkey" FOREIGN KEY ("blocked_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "stranger_users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "stranger_users_rate_limit_rpm_check" CHECK ((rate_limit_rpm IS NULL) OR (rate_limit_rpm > 0))
);
-- Create index "idx_stranger_users_ip" to table: "stranger_users"
CREATE INDEX "idx_stranger_users_ip" ON "stranger_users" ("org_id", "ip_address");
-- Create index "idx_stranger_users_last_active" to table: "stranger_users"
CREATE INDEX "idx_stranger_users_last_active" ON "stranger_users" ("org_id", "last_active_at" DESC);
-- Create index "idx_stranger_users_org" to table: "stranger_users"
CREATE INDEX "idx_stranger_users_org" ON "stranger_users" ("org_id");
-- Create index "idx_stranger_users_org_status" to table: "stranger_users"
CREATE INDEX "idx_stranger_users_org_status" ON "stranger_users" ("org_id", "status");
-- Create "subscriptions" table
CREATE TABLE "subscriptions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "org_id" uuid NOT NULL,
  "plan_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "hyperswitch_subscription_id" text NULL,
  "current_period_start" timestamptz NOT NULL DEFAULT now(),
  "current_period_end" timestamptz NOT NULL DEFAULT (now() + '1 mon'::interval),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "seat_count" integer NOT NULL DEFAULT 1,
  "billing_cycle" text NOT NULL DEFAULT 'monthly',
  "trial_ends_at" timestamptz NULL,
  "grace_period_ends_at" timestamptz NULL,
  "refund_id" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "subscriptions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "subscriptions_billing_cycle_check" CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'annual'::text])),
  CONSTRAINT "subscriptions_status_check" CHECK (status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'trialing'::text, 'paused'::text, 'expired'::text]))
);
-- Create index "idx_subscriptions_hyperswitch_id" to table: "subscriptions"
CREATE INDEX "idx_subscriptions_hyperswitch_id" ON "subscriptions" ("hyperswitch_subscription_id") WHERE (hyperswitch_subscription_id IS NOT NULL);
-- Create index "idx_subscriptions_org_active" to table: "subscriptions"
CREATE UNIQUE INDEX "idx_subscriptions_org_active" ON "subscriptions" ("org_id") WHERE (status = ANY (ARRAY['active'::text, 'trialing'::text, 'past_due'::text]));
-- Create "user_identities" table
CREATE TABLE "user_identities" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "anonymous_id" character varying(255) NOT NULL,
  "user_id" uuid NULL,
  "posthog_distinct_id" character varying(255) NULL,
  "channel" character varying(50) NOT NULL DEFAULT 'chat',
  "first_seen_at" timestamptz NOT NULL DEFAULT now(),
  "last_seen_at" timestamptz NOT NULL DEFAULT now(),
  "session_count" integer NOT NULL DEFAULT 1,
  "metadata" jsonb NULL DEFAULT '{}',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "user_identities_org_id_anonymous_id_channel_key" UNIQUE ("org_id", "anonymous_id", "channel"),
  CONSTRAINT "user_identities_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_identities_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "idx_user_identities_anonymous" to table: "user_identities"
CREATE INDEX "idx_user_identities_anonymous" ON "user_identities" ("org_id", "anonymous_id");
-- Create index "idx_user_identities_channel" to table: "user_identities"
CREATE INDEX "idx_user_identities_channel" ON "user_identities" ("org_id", "channel");
-- Create index "idx_user_identities_last_seen" to table: "user_identities"
CREATE INDEX "idx_user_identities_last_seen" ON "user_identities" ("org_id", "last_seen_at" DESC);
-- Create index "idx_user_identities_org" to table: "user_identities"
CREATE INDEX "idx_user_identities_org" ON "user_identities" ("org_id");
-- Create index "idx_user_identities_user" to table: "user_identities"
CREATE INDEX "idx_user_identities_user" ON "user_identities" ("user_id") WHERE (user_id IS NOT NULL);
-- Create "user_notification_preferences" table
CREATE TABLE "user_notification_preferences" (
  "user_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "email_summaries_enabled" boolean NOT NULL DEFAULT false,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "workspace_id"),
  CONSTRAINT "user_notification_preferences_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_notification_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_notification_preferences_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_user_notification_preferences_org" to table: "user_notification_preferences"
CREATE INDEX "idx_user_notification_preferences_org" ON "user_notification_preferences" ("org_id");
-- Create "user_passkey_labels" table
CREATE TABLE "user_passkey_labels" (
  "user_id" uuid NOT NULL,
  "credential_id" text NOT NULL,
  "label" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "last_used_at" timestamptz NULL,
  PRIMARY KEY ("credential_id"),
  CONSTRAINT "user_passkey_labels_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "user_passkey_labels_label_check" CHECK ((length(label) >= 1) AND (length(label) <= 255))
);
-- Create index "idx_user_passkey_labels_user_id" to table: "user_passkey_labels"
CREATE INDEX "idx_user_passkey_labels_user_id" ON "user_passkey_labels" ("user_id");
-- Create "voice_sessions" table
CREATE TABLE "voice_sessions" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "user_id" uuid NULL,
  "stranger_id" uuid NULL,
  "livekit_room" character varying(255) NOT NULL,
  "state" "voice_session_state" NOT NULL DEFAULT 'created',
  "started_at" timestamptz NULL,
  "ended_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "call_duration_seconds" integer NULL GENERATED ALWAYS AS (
CASE
    WHEN ((started_at IS NOT NULL) AND (ended_at IS NOT NULL)) THEN (EXTRACT(epoch FROM (ended_at - started_at)))::integer
    ELSE NULL::integer
END) STORED,
  PRIMARY KEY ("id"),
  CONSTRAINT "voice_sessions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "voice_sessions_stranger_id_fkey" FOREIGN KEY ("stranger_id") REFERENCES "stranger_users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "voice_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "chk_voice_session_actor" CHECK (((user_id IS NOT NULL) AND (stranger_id IS NULL)) OR ((user_id IS NULL) AND (stranger_id IS NOT NULL)) OR ((user_id IS NULL) AND (stranger_id IS NULL))),
  CONSTRAINT "chk_voice_session_times" CHECK ((started_at IS NULL) OR (ended_at IS NULL) OR (ended_at >= started_at))
);
-- Create index "idx_voice_sessions_org" to table: "voice_sessions"
CREATE INDEX "idx_voice_sessions_org" ON "voice_sessions" ("org_id");
-- Create index "idx_voice_sessions_org_created" to table: "voice_sessions"
CREATE INDEX "idx_voice_sessions_org_created" ON "voice_sessions" ("org_id", "created_at" DESC);
-- Create index "idx_voice_sessions_org_state" to table: "voice_sessions"
CREATE INDEX "idx_voice_sessions_org_state" ON "voice_sessions" ("org_id", "state");
-- Create index "idx_voice_sessions_stranger" to table: "voice_sessions"
CREATE INDEX "idx_voice_sessions_stranger" ON "voice_sessions" ("org_id", "stranger_id") WHERE (stranger_id IS NOT NULL);
-- Create index "idx_voice_sessions_user" to table: "voice_sessions"
CREATE INDEX "idx_voice_sessions_user" ON "voice_sessions" ("org_id", "user_id") WHERE (user_id IS NOT NULL);
-- Create "voice_turns" table
CREATE TABLE "voice_turns" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "session_id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "speaker" "voice_speaker" NOT NULL,
  "transcript" text NOT NULL,
  "started_at" timestamptz NOT NULL,
  "ended_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "voice_turns_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "voice_turns_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "voice_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chk_voice_turn_times" CHECK ((ended_at IS NULL) OR (ended_at >= started_at))
);
-- Create index "idx_voice_turns_org" to table: "voice_turns"
CREATE INDEX "idx_voice_turns_org" ON "voice_turns" ("org_id");
-- Create index "idx_voice_turns_session" to table: "voice_turns"
CREATE INDEX "idx_voice_turns_session" ON "voice_turns" ("session_id");
-- Create index "idx_voice_turns_session_started" to table: "voice_turns"
CREATE INDEX "idx_voice_turns_session_started" ON "voice_turns" ("session_id", "started_at");
-- Create "voice_usage_summaries" table
CREATE TABLE "voice_usage_summaries" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "period_start" timestamptz NOT NULL,
  "total_sessions" integer NOT NULL DEFAULT 0,
  "total_duration_seconds" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_voice_usage_org_period" UNIQUE ("org_id", "period_start"),
  CONSTRAINT "voice_usage_summaries_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_voice_usage_org" to table: "voice_usage_summaries"
CREATE INDEX "idx_voice_usage_org" ON "voice_usage_summaries" ("org_id");
-- Create index "idx_voice_usage_period" to table: "voice_usage_summaries"
CREATE INDEX "idx_voice_usage_period" ON "voice_usage_summaries" ("org_id", "period_start" DESC);
-- Create "webhook_configs" table
CREATE TABLE "webhook_configs" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "name" character varying(255) NOT NULL,
  "url" text NOT NULL,
  "secret" character varying(255) NOT NULL,
  "events" text[] NOT NULL,
  "headers" jsonb NULL DEFAULT '{}',
  "status" "webhook_status" NOT NULL DEFAULT 'active',
  "max_retries" integer NOT NULL DEFAULT 5,
  "last_triggered_at" timestamptz NULL,
  "failure_count" integer NOT NULL DEFAULT 0,
  "created_by" uuid NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "webhook_configs_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "webhook_configs_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_webhook_configs_events" to table: "webhook_configs"
CREATE INDEX "idx_webhook_configs_events" ON "webhook_configs" USING GIN ("events");
-- Create index "idx_webhook_configs_id_org" to table: "webhook_configs"
CREATE UNIQUE INDEX "idx_webhook_configs_id_org" ON "webhook_configs" ("id", "org_id");
-- Create index "idx_webhook_configs_org" to table: "webhook_configs"
CREATE INDEX "idx_webhook_configs_org" ON "webhook_configs" ("org_id");
-- Create index "idx_webhook_configs_status" to table: "webhook_configs"
CREATE INDEX "idx_webhook_configs_status" ON "webhook_configs" ("org_id", "status") WHERE (status = 'active'::webhook_status);
-- Create "webhook_deliveries" table
CREATE TABLE "webhook_deliveries" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "webhook_id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "event_type" character varying(100) NOT NULL,
  "payload" jsonb NOT NULL,
  "status" character varying(50) NOT NULL DEFAULT 'pending',
  "attempt" integer NOT NULL DEFAULT 0,
  "response_status" integer NULL,
  "response_body" text NULL,
  "next_retry_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "completed_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_webhook_deliveries_config" FOREIGN KEY ("webhook_id", "org_id") REFERENCES "webhook_configs" ("id", "org_id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "webhook_deliveries_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_webhook_deliveries_org" to table: "webhook_deliveries"
CREATE INDEX "idx_webhook_deliveries_org" ON "webhook_deliveries" ("org_id");
-- Create index "idx_webhook_deliveries_retry" to table: "webhook_deliveries"
CREATE INDEX "idx_webhook_deliveries_retry" ON "webhook_deliveries" ("next_retry_at") WHERE ((status)::text = 'pending'::text);
-- Create index "idx_webhook_deliveries_status" to table: "webhook_deliveries"
CREATE INDEX "idx_webhook_deliveries_status" ON "webhook_deliveries" ("webhook_id", "status");
-- Create index "idx_webhook_deliveries_webhook" to table: "webhook_deliveries"
CREATE INDEX "idx_webhook_deliveries_webhook" ON "webhook_deliveries" ("webhook_id");
-- Create "whatsapp_phone_numbers" table
CREATE TABLE "whatsapp_phone_numbers" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "phone_number" character varying(20) NOT NULL,
  "display_name" character varying(255) NOT NULL DEFAULT '',
  "waba_id" character varying(64) NOT NULL,
  "verified" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_whatsapp_phone_org" UNIQUE ("org_id", "phone_number"),
  CONSTRAINT "whatsapp_phone_numbers_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_whatsapp_phones_org" to table: "whatsapp_phone_numbers"
CREATE INDEX "idx_whatsapp_phones_org" ON "whatsapp_phone_numbers" ("org_id");
-- Create index "idx_whatsapp_phones_waba" to table: "whatsapp_phone_numbers"
CREATE INDEX "idx_whatsapp_phones_waba" ON "whatsapp_phone_numbers" ("waba_id");
-- Create "whatsapp_calls" table
CREATE TABLE "whatsapp_calls" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "call_id" character varying(128) NOT NULL,
  "phone_number_id" uuid NOT NULL,
  "direction" "whatsapp_call_direction" NOT NULL,
  "state" "whatsapp_call_state" NOT NULL DEFAULT 'ringing',
  "caller" character varying(20) NOT NULL,
  "callee" character varying(20) NOT NULL,
  "started_at" timestamptz NULL,
  "ended_at" timestamptz NULL,
  "duration_seconds" integer NULL GENERATED ALWAYS AS (
CASE
    WHEN ((started_at IS NOT NULL) AND (ended_at IS NOT NULL)) THEN (EXTRACT(epoch FROM (ended_at - started_at)))::integer
    ELSE NULL::integer
END) STORED,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "uq_whatsapp_call_id" UNIQUE ("call_id"),
  CONSTRAINT "whatsapp_calls_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "whatsapp_calls_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "whatsapp_phone_numbers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "chk_whatsapp_call_times" CHECK ((started_at IS NULL) OR (ended_at IS NULL) OR (ended_at >= started_at))
);
-- Create index "idx_whatsapp_calls_call_id" to table: "whatsapp_calls"
CREATE INDEX "idx_whatsapp_calls_call_id" ON "whatsapp_calls" ("call_id");
-- Create index "idx_whatsapp_calls_org" to table: "whatsapp_calls"
CREATE INDEX "idx_whatsapp_calls_org" ON "whatsapp_calls" ("org_id");
-- Create index "idx_whatsapp_calls_org_created" to table: "whatsapp_calls"
CREATE INDEX "idx_whatsapp_calls_org_created" ON "whatsapp_calls" ("org_id", "created_at" DESC);
-- Create index "idx_whatsapp_calls_org_state" to table: "whatsapp_calls"
CREATE INDEX "idx_whatsapp_calls_org_state" ON "whatsapp_calls" ("org_id", "state");
-- Create index "idx_whatsapp_calls_phone" to table: "whatsapp_calls"
CREATE INDEX "idx_whatsapp_calls_phone" ON "whatsapp_calls" ("phone_number_id");
-- Create "workspace_members" table
CREATE TABLE "workspace_members" (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
  "workspace_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" "workspace_role" NOT NULL DEFAULT 'member',
  "org_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "workspace_members_workspace_id_user_id_key" UNIQUE ("workspace_id", "user_id"),
  CONSTRAINT "workspace_members_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "workspace_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "workspace_members_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "idx_workspace_members_org_id" to table: "workspace_members"
CREATE INDEX "idx_workspace_members_org_id" ON "workspace_members" ("org_id");
-- Create index "idx_workspace_members_user_id" to table: "workspace_members"
CREATE INDEX "idx_workspace_members_user_id" ON "workspace_members" ("user_id");
-- Create index "idx_workspace_members_workspace_id" to table: "workspace_members"
CREATE INDEX "idx_workspace_members_workspace_id" ON "workspace_members" ("workspace_id");
